import { useEffect, useRef, useState } from "react";
import { Cloud, Database, Check, Download, HardDrive, Import, RefreshCw, ShieldCheck, Upload, WifiOff, CircleHelp, HeartPulse, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { type ExecutionMode } from "@/lib/executionMode";

function formatBytes(size = 0) {
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}

function formatSync(value?: string) {
  if (!value || value === new Date(0).toISOString()) return "Not written yet";
  return new Date(value).toLocaleString();
}

export default function SettingsView() {
  const { data: settings, isLoading } = trpc.settings.get.useQuery();
  const utils = trpc.useUtils();
  const fileInput = useRef<HTMLInputElement>(null);
  const [selectedMode, setSelectedMode] = useState<ExecutionMode>("cloud");
  const [showWizard, setShowWizard] = useState(false);
  const [modelForm, setModelForm] = useState({ provider: "llama.cpp", modelName: "", modelPath: "", apiBaseUrl: "" });
  const setMode = trpc.settings.setExecutionMode.useMutation({
    onSuccess: (next) => {
      setSelectedMode(next.executionMode);
      localStorage.setItem("agent-ops-execution-mode", next.executionMode);
      window.dispatchEvent(new CustomEvent("agent-ops:execution-mode", { detail: { mode: next.executionMode } }));
      void utils.settings.get.invalidate();
      toast.success(next.executionMode === "offline" ? "Offline mode enabled" : "Cloud mode enabled", { description: next.executionMode === "offline" ? "New work is limited to local/offline specialists." : "Cloud-connected specialists are available again." });
    },
    onError: (error) => toast.error("Could not save execution mode", { description: error.message }),
  });
  const saveLocalModel = trpc.settings.saveLocalModel.useMutation({
    onSuccess: () => { setShowWizard(false); void utils.settings.get.invalidate(); toast.success("Local model setup saved", { description: "Offline mode is ready for disconnected execution." }); },
    onError: (error) => toast.error("Could not save local model setup", { description: error.message }),
  });
  const healthCheck = trpc.settings.healthCheckLocalModel.useMutation({ onSuccess: (result) => { void utils.settings.get.invalidate(); toast[result.ready ? "success" : "error"](result.ready ? "Local model is healthy" : "Local model health check failed", { description: result.message }); }, onError: (error) => toast.error("Health check failed", { description: error.message }) });
  const discoverPaths = trpc.settings.discoverModelPaths.useQuery();
  const exportBackup = trpc.settings.exportBackup.useMutation({
    onSuccess: ({ filename, serialized }) => { const url = URL.createObjectURL(new Blob([serialized], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); toast.success("Backup exported", { description: "Keep the JSON file somewhere safe before changing USB drives." }); },
    onError: (error) => toast.error("Could not export backup", { description: error.message }),
  });
  const importBackup = trpc.settings.importBackup.useMutation({
    onSuccess: (next) => { localStorage.setItem("agent-ops-execution-mode", next.executionMode); window.dispatchEvent(new CustomEvent("agent-ops:execution-mode", { detail: { mode: next.executionMode } })); void utils.settings.get.invalidate(); toast.success("Backup restored", { description: next.snapshotPath ? `A pre-restore snapshot was saved at ${next.snapshotPath}.` : "The workspace state and execution mode were restored from JSON." }); },
    onError: (error) => toast.error("Backup restore failed", { description: error.message }),
  });

  useEffect(() => {
    if (settings?.executionMode) setSelectedMode(settings.executionMode);
    if (settings?.localModel && typeof settings.localModel === "object") setModelForm((current) => ({ ...current, ...(settings.localModel as typeof current), apiBaseUrl: (settings.localModel as typeof current).apiBaseUrl || "" }));
    if (settings?.isFirstRun) setShowWizard(true);
  }, [settings?.executionMode, settings?.localModel, settings?.isFirstRun]);

  const chooseMode = (mode: ExecutionMode) => { if (mode === selectedMode || setMode.isPending) return; setSelectedMode(mode); setMode.mutate({ executionMode: mode }); };
  const offline = selectedMode === "offline";
  const submitModel = (event: React.FormEvent) => { event.preventDefault(); saveLocalModel.mutate({ ...modelForm, apiBaseUrl: modelForm.apiBaseUrl || undefined }); };
  const useDiscoveredPath = (path: string) => setModelForm((current) => ({ ...current, modelPath: path }));
  const handleImportFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { importBackup.mutate({ serialized: await file.text() }); } catch { toast.error("Could not read backup file"); } finally { event.target.value = ""; } };

  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-cyan-300/80"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300" />User settings</div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white">Choose how the desk operates.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-400">Switch between self-contained Offline work and cloud-connected operation. Your choice is saved to the local JSON state file and restored when the portable runtime starts again.</p></div><Tooltip><TooltipTrigger asChild><Badge tabIndex={0} variant="outline" className={offline ? "cursor-help border-amber-300/25 bg-amber-300/10 px-3 py-1.5 text-amber-200" : "cursor-help border-emerald-300/25 bg-emerald-300/10 px-3 py-1.5 text-emerald-200"}><span className={`mr-2 inline-block h-1.5 w-1.5 rounded-full ${offline ? "bg-amber-300" : "bg-emerald-300"}`} />{offline ? "Offline mode active" : "Cloud mode active"}<CircleHelp className="ml-1.5 h-3.5 w-3.5 opacity-60" /></Badge></TooltipTrigger><TooltipContent side="bottom" className="max-w-xs"><p className="font-medium">{offline ? "Offline" : "Cloud"} mode</p><p className="mt-1 opacity-80">Last sync: {formatSync(settings?.lastSyncAt)} · Data store: {formatBytes(settings?.sizeBytes)}</p></TooltipContent></Tooltip></div>
    {showWizard && <Card className="border-cyan-300/25 bg-cyan-300/[0.06] shadow-none"><CardHeader className="px-5 py-5"><CardTitle className="flex items-center gap-2 text-base font-semibold text-white"><HardDrive className="h-4 w-4 text-cyan-300" />Set up disconnected execution</CardTitle><p className="mt-1 text-xs leading-relaxed text-slate-400">This first-run guide records where your local model lives. No cloud credentials are required for the model itself.</p></CardHeader><CardContent><form onSubmit={submitModel} className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="model-provider">Provider</Label><Input id="model-provider" value={modelForm.provider} onChange={(event) => setModelForm({ ...modelForm, provider: event.target.value })} placeholder="llama.cpp, Ollama, or LM Studio" /></div><div><Label htmlFor="model-name">Model name</Label><Input id="model-name" required value={modelForm.modelName} onChange={(event) => setModelForm({ ...modelForm, modelName: event.target.value })} placeholder="llama-3.1-8b-instruct" /></div><div className="md:col-span-2"><Label htmlFor="model-path">Local model path or endpoint</Label><Input id="model-path" required value={modelForm.modelPath} onChange={(event) => setModelForm({ ...modelForm, modelPath: event.target.value })} placeholder="/Volumes/USB/models/model.gguf or http://127.0.0.1:11434" /><p className="mt-1 text-[11px] text-slate-500">Use a USB-relative path where possible so the setup remains portable across hosts.</p>{discoverPaths.data?.candidates?.length ? <div className="mt-3 rounded-lg border border-white/[0.07] bg-black/15 p-3"><div className="mb-2 flex items-center gap-2 text-[11px] font-medium text-slate-300"><Search className="h-3.5 w-3.5 text-cyan-300" />Discovered {discoverPaths.data.platform} USB paths</div><div className="flex flex-wrap gap-2">{discoverPaths.data.candidates.map((path) => <button type="button" key={path} onClick={() => useDiscoveredPath(path)} className="rounded-md border border-white/[0.08] px-2 py-1 font-mono text-[10px] text-slate-500 transition hover:border-cyan-300/30 hover:text-cyan-200">{path}</button>)}</div></div> : null}</div><div><Label htmlFor="model-api">Optional local API URL</Label><Input id="model-api" value={modelForm.apiBaseUrl} onChange={(event) => setModelForm({ ...modelForm, apiBaseUrl: event.target.value })} placeholder="http://127.0.0.1:11434" /></div><div className="flex items-end justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setShowWizard(false)} className="text-slate-400">Later</Button><Button type="submit" disabled={saveLocalModel.isPending}>{saveLocalModel.isPending ? "Saving…" : "Save local model"}</Button></div></form></CardContent></Card>}
    <Card className={`border shadow-none ${offline ? "border-amber-300/20 bg-amber-300/[0.045]" : "border-emerald-300/20 bg-emerald-300/[0.045]"}`}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${offline ? "border-amber-300/25 bg-amber-300/10 text-amber-200" : "border-emerald-300/25 bg-emerald-300/10 text-emerald-200"}`}>{offline ? <WifiOff className="h-5 w-5" /> : <Cloud className="h-5 w-5" />}</div><div><p className="text-sm font-semibold text-white">Current mode: {offline ? "Offline" : "Cloud"}</p><p className="mt-1 text-xs leading-relaxed text-slate-400">{offline ? "Cloud-only agents are blocked. Approvals, audit logs, emergency stops, and local specialists remain available." : "Cloud-connected agents may run when allowed by workspace guardrails. Sensitive actions still require your approval."}</p></div></div><div className="flex items-center gap-2 text-xs text-slate-500"><Check className="h-4 w-4 text-emerald-300" />{isLoading ? "Loading saved preference…" : `Saved locally · ${formatBytes(settings?.sizeBytes)}`}</div></CardContent></Card>
    <Card className="border-white/[0.07] bg-white/[0.035] shadow-none"><CardHeader className="px-5 py-5"><CardTitle className="text-base font-semibold text-white">Execution mode</CardTitle><p className="mt-1 text-xs text-slate-500">Choose one mode manually. The change takes effect immediately for new workflow launches.</p></CardHeader><CardContent className="grid gap-3 p-5 pt-0 md:grid-cols-2"><button onClick={() => chooseMode("offline")} aria-pressed={offline} className={`rounded-2xl border p-5 text-left transition hover:-translate-y-0.5 focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/60 ${offline ? "border-amber-300/45 bg-amber-300/[0.08]" : "border-white/[0.08] bg-black/10 hover:bg-white/[0.05]"}`}><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-amber-300/25 bg-amber-300/10 text-amber-200"><HardDrive className="h-5 w-5" /></div>{offline && <span className="rounded-full bg-amber-300 px-2 py-1 text-[10px] font-semibold text-slate-950">Selected</span>}</div><p className="mt-4 text-sm font-semibold text-white">Offline</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Use local/offline model agents and keep the operating preference in the portable JSON store. No cloud-only launches are allowed.</p></button><button onClick={() => chooseMode("cloud")} aria-pressed={!offline} className={`rounded-2xl border p-5 text-left transition hover:-translate-y-0.5 focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/60 ${!offline ? "border-emerald-300/45 bg-emerald-300/[0.08]" : "border-white/[0.08] bg-black/10 hover:bg-white/[0.05]"}`}><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-emerald-300/25 bg-emerald-300/10 text-emerald-200"><Cloud className="h-5 w-5" /></div>{!offline && <span className="rounded-full bg-emerald-300 px-2 py-1 text-[10px] font-semibold text-slate-950">Selected</span>}</div><p className="mt-4 text-sm font-semibold text-white">Cloud</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Use connected model agents and integrations while preserving approval gates, audit logs, and emergency-stop controls.</p></button></CardContent></Card>
    <Card className="border-white/[0.07] bg-white/[0.035] shadow-none"><CardHeader className="px-5 py-5"><CardTitle className="flex items-center gap-2 text-base font-semibold text-white"><Database className="h-4 w-4 text-cyan-300" />Local persistence</CardTitle><p className="mt-1 text-xs text-slate-500">Offline mode stores application data in a local JSON file that can be backed up and restored manually.</p></CardHeader><CardContent className="space-y-3 p-5 pt-0"><div className="flex flex-col gap-3 rounded-xl border border-white/[0.07] bg-black/15 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-medium text-slate-300">State file</p><p className="mt-1 break-all font-mono text-[11px] text-slate-500">{settings?.storagePath || "portable-data/agent-ops-state.json"}</p><p className="mt-1 text-[11px] text-slate-600">{formatBytes(settings?.sizeBytes)} · last sync {formatSync(settings?.lastSyncAt)}</p></div><RefreshCw className={`h-4 w-4 shrink-0 text-slate-600 ${setMode.isPending || importBackup.isPending ? "animate-spin" : ""}`} /></div><div className={`rounded-xl border p-4 ${settings?.localModelReady ? "border-emerald-300/20 bg-emerald-300/[0.04]" : "border-amber-300/20 bg-amber-300/[0.04]"}`}><p className="text-xs font-semibold text-white">Offline readiness: {settings?.localModelReady ? "Ready" : "Setup required"}</p><p className="mt-1 text-xs leading-relaxed text-slate-400">{settings?.localModelMessage || "Configure a local model before launching fully disconnected work."}</p></div><div className="flex flex-col gap-2 sm:flex-row"><Button variant="outline" onClick={() => healthCheck.mutate()} disabled={healthCheck.isPending || !settings?.localModel} className="gap-2"><HeartPulse className="h-4 w-4" />{healthCheck.isPending ? "Checking…" : "Check local model"}</Button><Button variant="outline" onClick={() => exportBackup.mutate()} disabled={exportBackup.isPending} className="gap-2"><Download className="h-4 w-4" />{exportBackup.isPending ? "Preparing…" : "Export JSON backup"}</Button><input ref={fileInput} type="file" accept="application/json,.json" className="hidden" onChange={handleImportFile} /><Button variant="outline" onClick={() => fileInput.current?.click()} disabled={importBackup.isPending} className="gap-2"><Upload className="h-4 w-4" />{importBackup.isPending ? "Restoring…" : "Import JSON backup"}</Button><Button variant="ghost" onClick={() => setShowWizard(true)} className="gap-2 text-cyan-200"><Import className="h-4 w-4" />Local model setup</Button></div><div className="flex items-start gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.04] p-4"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" /><p className="text-xs leading-relaxed text-slate-400">Backups include workspace state and operational records. Restore only JSON files created by Agent Ops Desk, and keep an additional copy before importing.</p></div></CardContent></Card>
  </div>;
}
