import { and, desc, eq, gte, inArray, lte } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { agents, agentRuns, approvals, auditLogs, deliverables, executionLogs, policies, users, workflowSteps, workflows, workspaceState, type Agent, type InsertUser } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { publishRealtime } from "./realtime";
import { findLocal, insertLocal, listLocal, localPersistenceEnabled, removeLocal, updateLocal } from "./local-json-db";

let _db: ReturnType<typeof drizzle> | null = null;

export async function getDb() {
  if (!_db && process.env.DATABASE_URL) {
    try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; }
  }
  return _db;
}

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId };
  const updateSet: Record<string, unknown> = {};
  for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }
  if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; } else { values.lastSignedIn = new Date(); updateSet.lastSignedIn = new Date(); }
  if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; }
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}

export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }

export async function listAgents(): Promise<Agent[]> { if (localPersistenceEnabled()) return (await listLocal<Agent>("agents")).sort((a, b) => `${a.department}${a.name}`.localeCompare(`${b.department}${b.name}`)); const db = await getDb(); if (!db) return []; return db.select().from(agents).orderBy(agents.department, agents.name); }
export async function updateAgentStatus(id: number, status: "active" | "paused") { if (localPersistenceEnabled()) return updateLocal("agents", (row) => row.id === id, { status, updatedAt: new Date() }); const db = await getDb(); if (!db) return undefined; await db.update(agents).set({ status }).where(eq(agents.id, id)); return db.select().from(agents).where(eq(agents.id, id)).limit(1).then((rows) => rows[0]); }
export async function updateAgentConfig(id: number, config: { systemInstructions?: string | null; memory?: string | null; enabledSkills?: string[]; enabledConnectors?: string[] }) { if (localPersistenceEnabled()) return updateLocal("agents", (row) => row.id === id, { ...config, updatedAt: new Date() }); const db = await getDb(); if (!db) return undefined; await db.update(agents).set(config).where(eq(agents.id, id)); return db.select().from(agents).where(eq(agents.id, id)).limit(1).then((rows) => rows[0]); }
export async function getAgentById(id: number): Promise<Agent | undefined> { if (localPersistenceEnabled()) return findLocal<Agent>("agents", (row) => row.id === id); const db = await getDb(); if (!db) return undefined; return db.select().from(agents).where(eq(agents.id, id)).limit(1).then((rows) => rows[0]); }
export async function listRuns() { if (localPersistenceEnabled()) { const [runs, agentRows] = await Promise.all([listLocal("agentRuns"), listLocal("agents")]); const byId = new Map(agentRows.map((agent) => [agent.id, agent])); return runs.sort((a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt)).slice(0, 100).map((run) => ({ run, agent: byId.get(run.agentId) })); } const db = await getDb(); if (!db) return []; return db.select({ run: agentRuns, agent: agents }).from(agentRuns).leftJoin(agents, eq(agentRuns.agentId, agents.id)).orderBy(desc(agentRuns.updatedAt)).limit(100); }
export async function listApprovals() { if (localPersistenceEnabled()) { const [approvalRows, agentRows] = await Promise.all([listLocal("approvals"), listLocal("agents")]); const byId = new Map(agentRows.map((agent) => [agent.id, agent])); return approvalRows.filter((approval) => approval.status === "pending").sort((a, b) => +new Date(a.deadline) - +new Date(b.deadline)).map((approval) => ({ approval, agent: byId.get(approval.agentId) })); } const db = await getDb(); if (!db) return []; return db.select({ approval: approvals, agent: agents }).from(approvals).leftJoin(agents, eq(approvals.agentId, agents.id)).where(eq(approvals.status, "pending")).orderBy(approvals.deadline); }
export async function listAuditLogs() { if (localPersistenceEnabled()) return (await listLocal("auditLogs")).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)).slice(0, 200); const db = await getDb(); if (!db) return []; return db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(200); }
export async function listExecutionLogs(runId: number, range?: { from?: Date; to?: Date }) { if (localPersistenceEnabled()) return (await listLocal("executionLogs")).filter((row) => row.runId === runId && (!range?.from || new Date(row.createdAt) >= range.from) && (!range?.to || new Date(row.createdAt) <= range.to)).sort((a, b) => +new Date(a.createdAt) - +new Date(b.createdAt)); const db = await getDb(); if (!db) return []; const filters = [eq(executionLogs.runId, runId)]; if (range?.from) filters.push(gte(executionLogs.createdAt, range.from)); if (range?.to) filters.push(lte(executionLogs.createdAt, range.to)); return db.select().from(executionLogs).where(and(...filters)).orderBy(executionLogs.createdAt); }
export async function addExecutionLog(entry: typeof executionLogs.$inferInsert) { if (localPersistenceEnabled()) { const created = await insertLocal("executionLogs", { ...entry, createdAt: entry.createdAt || new Date() } as any); publishRealtime({ type: "execution-log.created", referenceKey: `RUN-${entry.runId}`, payload: { logId: created.id, runId: entry.runId, eventType: created.eventType, message: created.message } }); return created; } const db = await getDb(); if (!db) return undefined; await db.insert(executionLogs).values(entry); const created = await db.select().from(executionLogs).where(eq(executionLogs.runId, entry.runId)).orderBy(desc(executionLogs.createdAt)).limit(1).then((rows) => rows[0]); if (created) publishRealtime({ type: "execution-log.created", referenceKey: `RUN-${entry.runId}`, payload: { logId: created.id, runId: entry.runId, eventType: created.eventType, message: created.message } }); return created; }
export async function listPolicies() { if (localPersistenceEnabled()) { const [policyRows, agentRows] = await Promise.all([listLocal("policies"), listLocal("agents")]); const byId = new Map(agentRows.map((agent) => [agent.id, agent])); return policyRows.sort((a, b) => String(byId.get(a.agentId)?.name || "").localeCompare(String(byId.get(b.agentId)?.name || ""))).map((policy) => ({ policy, agent: byId.get(policy.agentId) })); } const db = await getDb(); if (!db) return []; return db.select({ policy: policies, agent: agents }).from(policies).leftJoin(agents, eq(policies.agentId, agents.id)).orderBy(agents.name); }
export async function getWorkspaceState() { if (localPersistenceEnabled()) { const row = await findLocal("workspaceState", (value) => value.id === 1); return row || { id: 1, globalKillSwitch: 0, updatedBy: "Local JSON", updatedAt: new Date(0) }; } const db = await getDb(); if (!db) return undefined; return db.select().from(workspaceState).where(eq(workspaceState.id, 1)).limit(1).then((rows) => rows[0]); }

export async function addAuditLog(entry: { eventType: string; actorType: "human" | "agent" | "system"; actorName: string; details: string; referenceKey?: string }) { if (localPersistenceEnabled()) { await insertLocal("auditLogs", { ...entry, createdAt: new Date() } as any); publishRealtime({ type: "audit.created", referenceKey: entry.referenceKey, payload: { eventType: entry.eventType, details: entry.details, actorName: entry.actorName } }); return; } const db = await getDb(); if (!db) return; await db.insert(auditLogs).values(entry); publishRealtime({ type: "audit.created", referenceKey: entry.referenceKey, payload: { eventType: entry.eventType, details: entry.details, actorName: entry.actorName } }); }

export async function getOverview() { const [agentRows, runRows, approvalRows] = await Promise.all([listAgents(), listRuns(), listApprovals()]); const byDepartment = new Map<string, { runs: number; approvals: number; queue: number; cycleSeconds: number }>(); for (const item of runRows) { const department = item.agent?.department || "Operations"; const entry = byDepartment.get(department) || { runs: 0, approvals: 0, queue: 0, cycleSeconds: 0 }; entry.runs += item.run.status === "completed" ? 1 : 0; entry.cycleSeconds += item.run.elapsedSeconds; byDepartment.set(department, entry); } for (const item of approvalRows) { const department = item.agent?.department || "Operations"; const entry = byDepartment.get(department) || { runs: 0, approvals: 0, queue: 0, cycleSeconds: 0 }; entry.queue += 1; byDepartment.set(department, entry); } return { activeRuns: runRows.filter((item) => item.run.status === "running").length, approvalQueue: approvalRows.length, spendCents: runRows.reduce((total, item) => total + item.run.costCents, 0), departments: Array.from(byDepartment.entries()).map(([name, value]) => ({ name, runs: value.runs, approval: value.approvals ? Math.round((value.approvals / Math.max(value.approvals + value.queue, 1)) * 100) : 100, cycleSeconds: value.runs ? Math.round(value.cycleSeconds / value.runs) : 0, queue: value.queue })), agents: agentRows.length }; }

export async function createRun(values: typeof agentRuns.$inferInsert) { if (localPersistenceEnabled()) return insertLocal("agentRuns", { ...values, startedAt: values.startedAt || new Date(), updatedAt: new Date() } as any); const db = await getDb(); if (!db) return undefined; await db.insert(agentRuns).values(values); return db.select().from(agentRuns).where(eq(agentRuns.runKey, values.runKey)).limit(1).then((rows) => rows[0]); }
export async function createApproval(values: typeof approvals.$inferInsert) { if (localPersistenceEnabled()) return insertLocal("approvals", { ...values, createdAt: values.createdAt || new Date() } as any); const db = await getDb(); if (!db) return undefined; await db.insert(approvals).values(values); return db.select().from(approvals).where(eq(approvals.approvalKey, values.approvalKey)).limit(1).then((rows) => rows[0]); }
export async function getRunByKey(runKey: string) { if (localPersistenceEnabled()) return findLocal("agentRuns", (row) => row.runKey === runKey); const db = await getDb(); if (!db) return undefined; return db.select().from(agentRuns).where(eq(agentRuns.runKey, runKey)).limit(1).then((rows) => rows[0]); }
export async function getRunById(id: number) { if (localPersistenceEnabled()) return findLocal("agentRuns", (row) => row.id === id); const db = await getDb(); if (!db) return undefined; return db.select().from(agentRuns).where(eq(agentRuns.id, id)).limit(1).then((rows) => rows[0]); }
export async function updateRunStatus(runKey: string, status: "running" | "waiting_approval" | "completed" | "paused" | "failed", currentStep: string) { if (localPersistenceEnabled()) { const before = await findLocal("agentRuns", (row) => row.runKey === runKey); const updated = await updateLocal("agentRuns", (row) => row.runKey === runKey, { status, currentStep, updatedAt: new Date() }); if (updated && before && (before.status !== status || before.currentStep !== currentStep)) await addExecutionLog({ runId: updated.id, eventType: "run.state_changed", actorType: "system", actorName: "Workflow runtime", step: currentStep, message: `${before.status} → ${status}`, metadata: { previousStep: before.currentStep, nextStep: currentStep } }); return updated; } const db = await getDb(); if (!db) return undefined; const before = await db.select().from(agentRuns).where(eq(agentRuns.runKey, runKey)).limit(1).then((rows) => rows[0]); await db.update(agentRuns).set({ status, currentStep }).where(eq(agentRuns.runKey, runKey)); const updated = await db.select().from(agentRuns).where(eq(agentRuns.runKey, runKey)).limit(1).then((rows) => rows[0]); if (updated && before && (before.status !== status || before.currentStep !== currentStep)) await addExecutionLog({ runId: updated.id, eventType: "run.state_changed", actorType: "system", actorName: "Workflow runtime", step: currentStep, message: `${before.status} → ${status}`, metadata: { previousStep: before.currentStep, nextStep: currentStep } }); return updated; }
export async function resolveApproval(id: number, status: "approved" | "denied" | "resubmitted", denialReason?: string, proposedAction?: string) { if (localPersistenceEnabled()) return updateLocal("approvals", (row) => row.id === id && row.status === "pending", { status, denialReason: status === "denied" ? denialReason : undefined, proposedAction: status === "resubmitted" && proposedAction ? proposedAction : undefined, resolvedAt: new Date() }); const db = await getDb(); if (!db) return undefined; await db.update(approvals).set({ status, denialReason: status === "denied" ? denialReason : undefined, proposedAction: status === "resubmitted" && proposedAction ? proposedAction : undefined, resolvedAt: new Date() }).where(and(eq(approvals.id, id), eq(approvals.status, "pending"))); return db.select().from(approvals).where(eq(approvals.id, id)).limit(1).then((rows) => rows[0]); }
export async function setGlobalKillSwitch(enabled: boolean, updatedBy: string) { if (localPersistenceEnabled()) { const activeRuns = enabled ? (await listLocal("agentRuns")).filter((run) => ["running", "waiting_approval"].includes(run.status)) : []; await updateLocal("workspaceState", (row) => row.id === 1, { globalKillSwitch: enabled ? 1 : 0, updatedBy, updatedAt: new Date() }); if (!(await findLocal("workspaceState", (row) => row.id === 1))) await insertLocal("workspaceState", { id: 1, globalKillSwitch: enabled ? 1 : 0, updatedBy, updatedAt: new Date() } as any); if (enabled) { for (const run of activeRuns) { await updateLocal("agentRuns", (row) => row.id === run.id, { status: "paused", currentStep: "Paused by global kill switch", updatedAt: new Date() }); await addExecutionLog({ runId: run.id, eventType: "emergency.stop", actorType: "system", actorName: updatedBy, step: "Paused by global kill switch", message: "Run frozen by global emergency stop", metadata: { previousStatus: run.status } }); } } return getWorkspaceState(); } const db = await getDb(); if (!db) return undefined; const activeRuns = enabled ? await db.select().from(agentRuns).where(inArray(agentRuns.status, ["running", "waiting_approval"])) : []; await db.update(workspaceState).set({ globalKillSwitch: enabled ? 1 : 0, updatedBy }).where(eq(workspaceState.id, 1)); if (enabled) { await db.update(agentRuns).set({ status: "paused", currentStep: "Paused by global kill switch" }).where(inArray(agentRuns.status, ["running", "waiting_approval"])); for (const run of activeRuns) await addExecutionLog({ runId: run.id, eventType: "emergency.stop", actorType: "system", actorName: updatedBy, step: "Paused by global kill switch", message: "Run frozen by global emergency stop", metadata: { previousStatus: run.status } }); } return getWorkspaceState(); }
export async function listWorkflows() { if (localPersistenceEnabled()) return (await listLocal("workflows")).sort((a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt)); const db = await getDb(); if (!db) return []; return db.select().from(workflows).orderBy(desc(workflows.updatedAt)); }
export async function updateWorkflow(id: number, values: { name: string; description: string; status?: "draft" | "published" | "paused" }, steps?: Array<Omit<typeof workflowSteps.$inferInsert, "workflowId">>) { if (localPersistenceEnabled()) { const updated = await updateLocal("workflows", (row) => row.id === id, { ...values, updatedAt: new Date() }); if (steps) { const current = await listLocal("workflowSteps"); await updateLocal("workflowSteps", (row) => row.workflowId === id, { deleted: true } as any); for (const step of steps) await insertLocal("workflowSteps", { ...step, workflowId: id } as any); void current; } return updated; } const db = await getDb(); if (!db) return undefined; await db.update(workflows).set(values).where(eq(workflows.id, id)); if (steps) { await db.delete(workflowSteps).where(eq(workflowSteps.workflowId, id)); if (steps.length) await db.insert(workflowSteps).values(steps.map((step) => ({ ...step, workflowId: id }))); } return db.select().from(workflows).where(eq(workflows.id, id)).limit(1).then((rows) => rows[0]); }
export async function deleteWorkflow(id: number) { if (localPersistenceEnabled()) { await removeLocal("workflowSteps", (row) => row.workflowId === id); await removeLocal("workflows", (row) => row.id === id); return; } const db = await getDb(); if (!db) return; await db.delete(workflowSteps).where(eq(workflowSteps.workflowId, id)); await db.delete(workflows).where(eq(workflows.id, id)); }
export async function resumeAgent(id: number) { if (localPersistenceEnabled()) return updateLocal("agents", (row) => row.id === id, { status: "active", updatedAt: new Date() }); const db = await getDb(); if (!db) return undefined; await db.update(agents).set({ status: "active" }).where(eq(agents.id, id)); return db.select().from(agents).where(eq(agents.id, id)).limit(1).then((rows) => rows[0]); }

export async function listWorkflowSteps(workflowId: number) { if (localPersistenceEnabled()) return (await listLocal("workflowSteps")).filter((row) => row.workflowId === workflowId && !row.deleted).sort((a, b) => a.position - b.position); const db = await getDb(); if (!db) return []; return db.select().from(workflowSteps).where(eq(workflowSteps.workflowId, workflowId)).orderBy(workflowSteps.position); }
export async function getWorkflowWithSteps(workflowId: number) { if (localPersistenceEnabled()) { const workflow = await findLocal("workflows", (row) => row.id === workflowId); return workflow ? { workflow, steps: await listWorkflowSteps(workflowId) } : undefined; } const db = await getDb(); if (!db) return undefined; const workflow = await db.select().from(workflows).where(eq(workflows.id, workflowId)).limit(1).then((rows) => rows[0]); return workflow ? { workflow, steps: await listWorkflowSteps(workflowId) } : undefined; }
export async function updateWorkflowStepTimeout(workflowId: number, stepKey: string, timeoutSeconds: number) { if (localPersistenceEnabled()) { const current = await findLocal("workflowSteps", (row) => row.workflowId === workflowId && row.stepKey === stepKey && !row.deleted); if (!current) return undefined; const config = { ...((current.config || {}) as Record<string, unknown>), timeoutSeconds }; return updateLocal("workflowSteps", (row) => row.id === current.id, { config }); } const db = await getDb(); if (!db) return undefined; const current = await db.select().from(workflowSteps).where(and(eq(workflowSteps.workflowId, workflowId), eq(workflowSteps.stepKey, stepKey))).limit(1).then((rows) => rows[0]); if (!current) return undefined; const config = { ...((current.config || {}) as Record<string, unknown>), timeoutSeconds }; await db.update(workflowSteps).set({ config }).where(eq(workflowSteps.id, current.id)); return { ...current, config }; }
export async function createWorkflow(values: typeof workflows.$inferInsert, steps: Array<Omit<typeof workflowSteps.$inferInsert, "workflowId">>) { if (localPersistenceEnabled()) { const workflow = await insertLocal("workflows", { ...values, createdAt: values.createdAt || new Date(), updatedAt: new Date() } as any); for (const step of steps) await insertLocal("workflowSteps", { ...step, workflowId: workflow.id } as any); return workflow; } const db = await getDb(); if (!db) return undefined; await db.insert(workflows).values(values); const workflow = await db.select().from(workflows).where(eq(workflows.workflowKey, values.workflowKey)).limit(1).then((rows) => rows[0]); if (workflow && steps.length) await db.insert(workflowSteps).values(steps.map((step) => ({ ...step, workflowId: workflow.id }))); return workflow; }
export async function listDeliverables() { if (localPersistenceEnabled()) { const [rows, agentRows, runRows] = await Promise.all([listLocal("deliverables"), listLocal("agents"), listLocal("agentRuns")]); const agentsById = new Map(agentRows.map((agent) => [agent.id, agent])); const runsById = new Map(runRows.map((run) => [run.id, run])); return rows.sort((a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt)).slice(0, 200).map((deliverable) => ({ deliverable, agent: agentsById.get(deliverable.agentId), run: runsById.get(deliverable.runId) })); } const db = await getDb(); if (!db) return []; return db.select({ deliverable: deliverables, agent: agents, run: agentRuns }).from(deliverables).leftJoin(agents, eq(deliverables.agentId, agents.id)).leftJoin(agentRuns, eq(deliverables.runId, agentRuns.id)).orderBy(desc(deliverables.updatedAt)).limit(200); }
export async function createDeliverable(values: typeof deliverables.$inferInsert) { if (localPersistenceEnabled()) return insertLocal("deliverables", { ...values, createdAt: values.createdAt || new Date(), updatedAt: new Date() } as any); const db = await getDb(); if (!db) return undefined; await db.insert(deliverables).values(values); return db.select().from(deliverables).where(eq(deliverables.deliverableKey, values.deliverableKey)).limit(1).then((rows) => rows[0]); }
